# Generated by Django 5.0.6 on 2024-07-04 19:13

import django_bleach.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_comment_email_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=django_bleach.models.BleachField(),
        ),
    ]
