# Generated by Django 5.0.6 on 2024-07-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_comment_url_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
